/* 肚肚小侦探 — entirely local, fictional play. No camera or remote services. */
'use strict';
const $ = (s) => document.querySelector(s);
const app = $('#app');
const DEFAULTS = { duration: 10, sound: true, haptics: true, motion: false };
const STORE = 'dudu-detective-preferences-v1';
const modes = {
  belly: { name:'肚肚', title:'零食吃太多', subtitle:'一起探秘小肚肚', color:'orange', number:'01', label:'肚肚探险', finding:'发现 3 处淘气虫活动', detail:'故事里的小虫正在开零食派对', childTitle:'肚肚想休息一下啦！', childText:'零食少一点，正餐香一点。\n和爸爸妈妈一起照顾小肚肚吧。', action:'我会少吃零食', steps:['零食先收好','好好吃正餐','和家人一起行动'], stages:['正在绘制肚肚轮廓','正在展开骨骼与器官层','正在寻找淘气虫的踪迹'], positions:[[40,47],[63,61],[44,72]] },
  hands: { name:'小手', title:'饭前没洗手', subtitle:'找找藏起来的小细菌', color:'blue', number:'02', label:'小手探险', finding:'发现 3 处细菌聚集', detail:'故事里的小细菌躲在指缝和手心', childTitle:'给小手洗个泡泡澡！', childText:'手心、手背、指缝都洗到。\n吃东西前，记得用肥皂认真洗手哦。', action:'我要去洗手', steps:['用水打湿小手','肥皂搓出泡泡','冲净擦干再吃饭'], stages:['正在绘制小手轮廓','正在展开手指骨骼层','正在寻找小细菌的藏身处'], positions:[[39,39],[62,47],[48,68]] },
  teeth: { name:'牙齿', title:'睡前不刷牙', subtitle:'守护亮晶晶的小牙齿', color:'purple', number:'03', label:'牙齿探险', finding:'发现 3 处牙齿清洁盲区', detail:'故事里的小牙菌正在悄悄躲猫猫', childTitle:'小牙齿也要说晚安！', childText:'和爸爸妈妈一起认真刷牙。\n让每一颗小牙齿，都穿上干净的睡衣。', action:'我要去刷牙', steps:['拿好自己的牙刷','每一面都认真刷','刷完和小牙说晚安'], stages:['正在绘制牙齿轮廓','正在展开牙齿结构层','正在寻找牙菌小斑点'], positions:[[35,40],[65,47],[48,60]] }
};
function readSettings() {
  try { const v=JSON.parse(localStorage.getItem(STORE)) || {}; return { duration:[5,10,15].includes(v.duration)?v.duration:10, ...Object.fromEntries(['sound','haptics','motion'].map(k=>[k,typeof v[k]==='boolean'?v[k]:DEFAULTS[k]])) }; }
  catch { return {...DEFAULTS}; }
}
let settings=readSettings(), activeMode='belly', screen='home', timer=0, scanStart=0, percent=0, lastBeat=-1;
let audioContext, voice, toastTimer, motionAllowed=false, orientationOrigin=null, motionTimer=0, scanToken=0;
let offlineReady=false, updateWaiting=null, wakeLock=null;
const canVibrate=typeof navigator.vibrate==='function';
const icons={
  settings:'<path d="M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8Z"/><path d="m10 3-1 3-3 1-3 1v3l3 1 1 3-1 3 3 2 2-2h3l2 2 3-2-1-3 1-3 3-1V8l-3-1-3-1-1-3Z"/>',
  arrow:'<path d="M5 12h14M13 6l6 6-6 6"/>',back:'<path d="m14 5-7 7 7 7"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',
  sound:'<path d="m11 5-5 4H3v6h3l5 4Z M15 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>',
  shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8 12 3 3 5-6"/>',
  download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',check:'<path d="m5 12 4 4L19 6"/>',
  star:'<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1 6.2-5.5-2.9-5.5 2.9 1-6.2L2 9.6l6.2-.9Z"/>',
  motion:'<rect x="7" y="3" width="10" height="18" rx="3"/><path d="m3 7-2 5 2 5m18-10 2 5-2 5M11 17h2"/>',
  scan:'<path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5M6 12h12"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v1"/>'
};
function icon(name){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.star}</svg>`;}
function buttonIcon(name,action,label){return `<button class="icon-button" data-action="${action}" aria-label="${label}">${icon(name)}</button>`;}
function badge(){return `<span class="simulation">${icon('star')} 模拟游戏 · 非医学诊断</span>`;}
function art(id,cls=''){return `<img class="character ${cls}" src="./assets/${id}.jpg" alt="卡通${modes[id].name}小伙伴" draggable="false">`;}
function header(title,back='home'){return `<header class="page-header">${buttonIcon('back',back,'返回')}<b>${title}</b><span class="header-spacer"></span></header>`;}
function home(){
 return `<header class="brand-header"><a class="brand" href="#home" aria-label="肚肚小侦探首页"><span class="brand-mark">${icon('scan')}</span><span>肚肚小侦探<small>好习惯探险队</small></span></a>${buttonIcon('settings','settings','设置')}</header>
 <section class="home-intro"><span class="eyebrow">HELLO, LITTLE EXPLORER!</span><h1>今天，探秘<span>哪里呀？<i>✦</i></span></h1><p>选个小任务，和好习惯一起玩。</p><span class="intro-doodle" aria-hidden="true">✳</span></section>
 <div class="scenario-list">${Object.entries(modes).map(([id,m])=>`<button class="scenario ${m.color}" data-action="start" data-mode="${id}"><span class="card-art">${art(id)}</span><span class="card-copy"><span class="card-kicker">MISSION ${m.number}</span><strong>${m.title}</strong><span class="card-subtitle">${m.subtitle}</span></span><span class="card-arrow">${icon('arrow')}</span></button>`).join('')}</div>
 <section class="home-note">${icon('shield')}<div><b>一场安心的亲子小游戏</b><p>不使用相机，画面和结果都是模拟的。</p></div></section>
 <footer class="home-footer"><span class="offline-state ${offlineReady?'ready':''}"><i></i>${offlineReady?'离线已就绪':'正在准备离线资源'}</span><button class="text-button" data-action="install">${icon('download')} 添加到桌面</button></footer>
 ${updateWaiting?'<button class="update-banner" data-action="update">新版本已准备好 · 点击更新</button>':''}
 <div class="bottom-caption">陪伴一点点，好习惯长大一点点。</div>`;
}
function anatomy(id){
 const common='<defs><linearGradient id="body-fill" x2="0" y2="1"><stop stop-color="#5aa8bd" stop-opacity=".26"/><stop offset="1" stop-color="#8edcc4" stop-opacity=".06"/></linearGradient></defs>';
 let shape='';
 if(id==='belly') shape=`<path class="outline" d="M106 40Q160 65 214 40L244 99 232 304Q160 337 88 304L76 99Z"/><g class="bones" fill="none">${[92,111,130,149].map((y,i)=>`<path d="M155 ${y}Q${91+i*4} ${y-22} ${94+i*4} ${y+5}Q112 ${y+22} 156 ${y+17}M165 ${y}Q${229-i*4} ${y-22} ${226-i*4} ${y+5}Q208 ${y+22} 164 ${y+17}"/>`).join('')}${[84,108,132,156,180,204,228,252,276].map(y=>`<rect x="155" y="${y}" width="10" height="13" rx="3"/>`).join('')}<path d="M100 269Q99 307 148 310L160 285 172 310Q221 307 220 269"/></g><g class="organs"><path d="M115 172Q100 176 109 200Q135 210 157 188L151 171Z"/><path d="M179 162Q195 159 197 177L191 201Q182 220 159 214Q139 205 151 192Q167 194 174 183Z"/><path class="gut" d="M117 228Q102 217 108 250Q108 269 126 266H194Q215 263 207 243Q208 224 189 230H132Q117 238 138 243H182Q198 252 180 258H139"/></g>`;
 if(id==='hands') shape=`<path class="outline" d="M114 302 97 255 48 201Q32 176 51 170Q64 170 92 198L81 102Q80 80 94 80Q108 79 110 99L121 161 119 55Q119 37 133 38Q147 38 148 57L153 151 157 46Q159 26 172 30Q185 33 183 53L183 154 194 76Q197 56 211 63Q222 68 218 86L211 183 230 124Q237 106 249 114Q258 122 251 140L229 225 205 267 201 302Z"/><g class="bones" fill="none"><path d="m160 268-44-58-60-24m104 82-32-68-29-96m61 164-7-71-18-139m25 210 13-72-3-143m-10 215 32-63 15-123m-47 186 46-42 34-98"/>${[[116,210],[128,200],[153,197],[173,196],[192,205],[206,226],[112,148],[143,125],[173,122],[201,148],[230,166]].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="5"/>`).join('')}</g>`;
 if(id==='teeth') shape=`<path class="outline" d="M160 63Q124 33 93 69Q62 102 90 163Q100 185 109 251Q115 299 131 272L153 206Q160 187 167 206L189 272Q205 299 211 251Q220 185 230 163Q258 102 227 69Q196 33 160 63Z"/><g class="bones" fill="none"><path d="M111 85Q137 71 160 89Q185 71 212 85M111 129Q159 150 209 129M115 145Q130 169 134 231M205 145Q190 169 186 231"/></g><g class="organs"><path d="M148 112Q160 97 172 112L175 148 188 229 163 175 157 175 132 229 145 148Z"/></g><g class="bones" fill="none"><path d="M84 309Q160 330 236 309M87 316l-1 13m31-7v13m29-10v14m29-14v14m29-17v13m30-18 1 13"/></g>`;
 return `<svg class="anatomy" viewBox="0 0 320 350" aria-label="${modes[id].name}虚构扫描示意图" role="img">${common}${shape}</svg>`;
}
function scanner(result=false){const m=modes[activeMode];return `<div class="scanner-screen ${m.color} ${result?'is-result':''}">
 <header class="scan-header">${buttonIcon('close','home','结束扫描并返回首页')}<b>${result?'扫描结果':'正在扫描'}<span id="header-percent">${result?'':` ${percent}%`}</span></b><span class="mini-tag">模拟效果</span></header>
 <div class="scan-title"><span class="eyebrow">${m.label} / ${result?'COMPLETE':'SCANNING'}</span><h1>${result?'小发现，大任务':`探秘${m.name}中…`}</h1></div>
 <div class="scan-window" id="scan-window"><div class="scan-grid"></div><div class="scan-label"><i></i>${result?'SIMULATION COMPLETE':'SIMULATION LIVE'}</div><div class="depth-layers" id="depth-layers">${anatomy(activeMode)}<div class="hotspots ${result?'visible':''}" id="hotspots">${m.positions.map(([x,y],i)=>`<span class="hotspot hotspot-${i}" style="left:${x}%;top:${y}%"><span>${activeMode==='belly'?'<svg class="worm" viewBox="0 0 40 40" aria-hidden="true"><path d="M9 29C-1 13 31 29 23 17S36 2 32 14" fill="none" stroke="currentColor" stroke-width="6" stroke-linecap="round"/><circle cx="32" cy="8" r="1" fill="#25403b"/></svg>':'✳'}</span><small>0${i+1}</small></span>`).join('')}</div></div><div class="scan-beam"></div><span class="corner tl"></span><span class="corner tr"></span><span class="corner bl"></span><span class="corner br"></span><span class="scan-scale left"></span><span class="scan-scale right"></span><span class="scan-bottom">${result?'3 个虚构标记':'图像模拟 · 本机生成'}</span></div>
 <p class="motion-hint" id="motion-hint">${icon('motion')}${settings.motion&&motionAllowed?'轻轻移动手机，看看不同扫描层':'在画面上轻轻滑动，看看不同扫描层'}</p>
 ${result?`<section class="result-summary"><h2><span class="finding-dot">!</span>${m.finding}</h2><p>${m.detail}</p><small>预设的游戏结果，不代表真实身体情况</small></section><div class="scan-actions"><button class="primary" data-action="child">给孩子看 ${icon('arrow')}</button><button class="secondary voice-button" data-action="voice">${icon('sound')} 播放提示音</button><button class="text-button" data-action="start" data-mode="${activeMode}">再扫描一次</button></div>`:`<div class="progress-info"><span id="stage-text">${m.stages[0]}</span><b id="progress-value">0%</b></div><div class="progress-track" role="progressbar" aria-label="模拟扫描进度" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div id="progress-fill"></div></div><div class="sensor-row"><span><i></i>轮廓层</span><span><i></i>结构层</span><span><i></i>趣味层</span></div><p class="scan-instruction">手机轻轻靠近${m.name}，不用接触身体</p>`}
 <footer class="scan-footer">${badge()}</footer></div>`;}
function child(){const m=modes[activeMode];return `<div class="child-screen ${m.color}">${header('给小朋友的发现','result')}<div class="child-topline">${icon('star')} 好习惯小任务 ${icon('star')}</div><div class="child-art">${art(activeMode)}<span class="child-sticker">一起加油！</span></div><h1>${m.childTitle}</h1><p class="child-description">${m.childText.replace('\n','<br>')}</p><div class="child-steps">${m.steps.map((s,i)=>`<span><i>${i+1}</i>${s}</span>`).join('')}</div><button class="primary" data-action="complete">${m.action} ${icon('check')}</button><button class="text-button voice-button" data-action="voice">${icon('sound')} 听听小提醒</button><footer>${badge()}<p>刚才是一个小游戏，我们一起养成好习惯。</p></footer></div>`;}
function complete(){const m=modes[activeMode];return `<div class="complete-screen ${m.color}">${header('好习惯，出发！')}<div class="celebration" aria-hidden="true">✦ <span>★</span> ✧</div><span class="eyebrow">A LITTLE STEP, A BIG HIGH FIVE</span><h1>约定好啦！<br><span>给你一个大大的赞</span></h1><div class="complete-art">${art(activeMode)}</div><p>现在就和爸爸妈妈<br>一起完成小任务吧。</p><button class="primary" data-action="home">完成，回到首页 ${icon('arrow')}</button><button class="secondary" data-action="start" data-mode="${activeMode}">再玩一次模拟扫描</button><footer>${badge()}</footer></div>`;}
function toggle(key,title,description,disabled=false){return `<div class="setting-row"><div><b id="label-${key}">${title}</b><p>${description}</p></div><button class="switch" role="switch" aria-labelledby="label-${key}" aria-checked="${disabled?false:settings[key]}" data-action="toggle" data-key="${key}" ${disabled?'disabled':''}><span></span></button></div>`;}
function settingsPage(){return `${header('设置')}<section class="settings-intro"><span class="eyebrow">MAKE IT YOURS</span><h1>小探险，你做主</h1><p>按你的节奏，陪孩子玩一会儿。</p></section><h2 class="section-label">扫描体验</h2><section class="settings-group"><div class="duration-setting"><div><b>扫描时长</b><span>给小发现留一点悬念</span></div><div class="segmented" role="group" aria-label="扫描时长">${[5,10,15].map(n=>`<button data-action="duration" data-value="${n}" aria-pressed="${settings.duration===n}">${n} 秒</button>`).join('')}</div></div>${toggle('sound','扫描音效','扫描时播放轻柔的电子音')}${toggle('haptics','触感反馈',canVibrate?'扫描完成时轻轻震动':'当前浏览器不支持震动（iPhone 属于此情况）',!canVibrate)}${toggle('motion','随手机移动','开启后允许读取手机倾斜，形成画面视差')}</section><p class="settings-note">移动权限只用于扫描画面。关闭或离开扫描页后，立即停止读取。</p><h2 class="section-label">关于这个小工具</h2><section class="settings-group">${[['install','添加到桌面','download'],['privacy','隐私说明','shield'],['about','使用说明','info']].map(([action,title,ic])=>`<button class="setting-link" data-action="${action}"><span>${icon(ic)}${title}</span>${icon('arrow')}</button>`).join('')}</section><button class="reset-button" data-action="reset">恢复默认设置</button><p class="version">肚肚小侦探 · 1.0.0<br>原创卡通亲子模拟工具</p>`;}
function privacy(){return `${header('隐私说明','settings')}<article class="document"><span class="eyebrow">LOCAL & PRIVATE</span><h1>小游戏，<br>也认真保护隐私。</h1><p class="document-date">更新日期：2026 年 9 月 7 日</p><section><h2>无需提供个人信息</h2><p>本应用无需注册或登录，不请求姓名、手机号、儿童信息，不使用相机或麦克风，不读取照片、位置、通讯录或健康数据。扫描画面和结果都是预先设计的虚构效果。</p></section><section><h2>哪些内容留在本机</h2><p>扫描时长、音效、触感、随手机移动这四项偏好通过浏览器本地存储保存。应用文件、卡通图片和提示音缓存在设备上用于离线启动。不保存扫描记录、孩子的影像或身体信息。</p><p>恢复默认设置会重置四项偏好。要删除全部缓存，请在 iPhone 的 Safari 网站数据设置中删除本网站数据；仅移除桌面图标不一定会清除缓存。</p></section><section><h2>手机移动权限</h2><p>仅在你开启“随手机移动”、同意系统权限且进入扫描或结果页时，应用读取设备方向。数据只在本机实时计算，不保存，不上传。离开扫描页或将应用切到后台后立即停止监听。</p></section><section><h2>网络与托管</h2><p>首次加载和在线检查更新需要从托管服务下载静态文件。部署到 GitHub Pages 后，GitHub 可能处理访问 IP、请求日志等基础托管信息，具体依其隐私政策。应用本身没有统计代码、广告、后台接口或第三方字体。</p></section><section><h2>关于模拟结果</h2><p>此工具是亲子情境小游戏，不是医疗设备。它不会检测身体、寄生虫、细菌或牙齿问题，也不能用于诊断。请把它当作共同参与的小剧场。</p></section></article>`;}
function about(){return `${header('使用说明','settings')}<article class="document"><span class="eyebrow">LET’S PLAY TOGETHER</span><h1>三步，开始小探险</h1><section><h2>01 · 选一个情境</h2><p>在首页选择零食、洗手或刷牙任务。扫描会自动开始，手机可轻轻靠近对应部位，无需接触身体。</p></section><section><h2>02 · 一起看扫描</h2><p>等待进度完成。可以在画面上滑动探索扫描层，也可以在设置中开启“随手机移动”。不允许运动权限也能正常玩。</p></section><section><h2>03 · 把提醒变成行动</h2><p>点击“给孩子看”，用大图和简单的话一起约定一个小任务。点击提示音可播放离线中文语音；离开当前页面会停止播放。</p></section><section><h2>在 iPhone 上离线使用</h2><p>先用 Safari 打开线上网址，添加到主屏幕。再从桌面图标打开，看到“离线已就绪”后可开启飞行模式试用。首次下载未完成或系统清理缓存后，需要联网重载。</p><button class="secondary" data-action="install">查看添加步骤</button></section><section><h2>关于这个版本</h2><p>这是独立制作的“肚肚小侦探”，参考公开描述中的三种亲子互动流程，使用原创卡通素材，与原“肚肚扫描”应用无隶属关系。</p><p>浏览器无法提供所有原生能力：iPhone 网页不支持通用震动接口；设备姿态需要系统授权。动画和提示音仍可独立运行。</p></section></article>`;}
function stopVoice(){if(voice){voice.pause();voice.currentTime=0;voice=null;}document.querySelectorAll('.voice-button').forEach(b=>{b.classList.remove('playing');b.setAttribute('aria-pressed','false');});}
function stopScan(){cancelAnimationFrame(timer);timer=0;scanToken++;stopMotion();if(wakeLock){wakeLock.release().catch(()=>{});wakeLock=null;}}
function render(next=screen){stopVoice();if(next!=='scan'&&next!=='result')stopScan();screen=next;document.body.classList.toggle('dark-page',next==='scan'||next==='result');app.innerHTML=({home,settings:settingsPage,privacy,about,scan:()=>scanner(false),result:()=>scanner(true),child,complete}[next]||home)();window.scrollTo(0,0);if(next==='scan'||next==='result'){bindParallax();startMotion();}if(next==='home')paintOffline();}
function navigate(next){if(next==='result'){if(!modes[activeMode])activeMode='belly';}location.hash=next; if(screen===next)render(next);}
window.addEventListener('hashchange',()=>{const next=location.hash.slice(1);if(next==='scan'){if(screen!=='scan'){location.replace('#home');}return;}render(['home','settings','privacy','about','result','child','complete'].includes(next)?next:'home');});
function save(){try{localStorage.setItem(STORE,JSON.stringify(settings));}catch{toast('当前无法保存设置，本次使用仍然有效。');}}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3400);}
function ensureAudio(){try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;if(!audioContext)audioContext=new Audio();if(audioContext.state==='suspended')audioContext.resume().catch(()=>{});}catch{}}
function beep(frequency=620,duration=.09,volume=.045,delay=0){if(!audioContext||audioContext.state!=='running')return;const osc=audioContext.createOscillator(),gain=audioContext.createGain(),t=audioContext.currentTime+delay;osc.type='sine';osc.frequency.setValueAtTime(frequency,t);gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(volume,t+.01);gain.gain.exponentialRampToValueAtTime(.0001,t+duration);osc.connect(gain);gain.connect(audioContext.destination);osc.start(t);osc.stop(t+duration+.02);}
async function startScan(id){
 if(!modes[id])return;stopScan();stopVoice();activeMode=id;percent=0;lastBeat=-1;ensureAudio();render('scan');history.pushState(null,'','#scan');const token=scanToken;scanStart=performance.now();
 if(settings.motion&&!motionAllowed&&typeof window.DeviceOrientationEvent?.requestPermission==='function'){motionAllowed=await enableMotion();if(token!==scanToken||screen!=='scan')return;startMotion();scanStart=performance.now();}
 if('wakeLock'in navigator){try{const lock=await navigator.wakeLock.request('screen');if(token===scanToken&&screen==='scan')wakeLock=lock;else lock.release().catch(()=>{});}catch{}}
 if(token!==scanToken||screen!=='scan')return;
 function tick(now){if(screen!=='scan'||token!==scanToken)return;percent=Math.min(100,Math.floor((now-scanStart)/(settings.duration*10)));$('#header-percent').textContent=` ${percent}%`;$('#progress-value').textContent=`${percent}%`;$('#progress-fill').style.width=`${percent}%`;$('.progress-track').setAttribute('aria-valuenow',percent);$('#stage-text').textContent=modes[id].stages[Math.min(2,Math.floor(percent/34))];$('#scan-window').style.setProperty('--reveal',`${Math.min(100,percent*1.4)}%`);if(percent>65)$('#hotspots').classList.add('visible');const beat=Math.floor((now-scanStart)/900);if(beat!==lastBeat){lastBeat=beat;if(settings.sound&&!document.hidden)beep(500+percent*3);}if(percent>=100){stopScan();if(settings.sound){beep(660,.16,.05);beep(880,.25,.04,.15);}if(settings.haptics&&canVibrate)navigator.vibrate([60,60,100]);history.replaceState(null,'','#result');render('result');return;}timer=requestAnimationFrame(tick);}timer=requestAnimationFrame(tick);
}
function setParallax(x,y){const layer=$('#depth-layers');if(layer)layer.style.transform=`translate(${x}px,${y}px) rotateY(${x*.4}deg) rotateX(${-y*.35}deg)`;}
function bindParallax(){const windowEl=$('#scan-window');windowEl.addEventListener('pointermove',e=>{const r=windowEl.getBoundingClientRect();setParallax(((e.clientX-r.left)/r.width-.5)*22,((e.clientY-r.top)/r.height-.5)*22);});windowEl.addEventListener('pointerleave',()=>setParallax(0,0));}
function orientation(e){if(e.beta==null||e.gamma==null)return;if(!orientationOrigin)orientationOrigin={b:e.beta,g:e.gamma};clearTimeout(motionTimer);setParallax(Math.max(-13,Math.min(13,(e.gamma-orientationOrigin.g)*.6)),Math.max(-13,Math.min(13,(e.beta-orientationOrigin.b)*.6)));}
function startMotion(){stopMotion();if(!settings.motion||document.hidden)return;const D=window.DeviceOrientationEvent;if(!D)return;if(typeof D.requestPermission!=='function')motionAllowed=true;if(!motionAllowed)return;window.addEventListener('deviceorientation',orientation);motionTimer=setTimeout(()=>{const hint=$('#motion-hint');if(hint&&!orientationOrigin)hint.innerHTML=icon('motion')+'暂未收到移动数据，可在画面上滑动';},2200);}
function stopMotion(){window.removeEventListener('deviceorientation',orientation);clearTimeout(motionTimer);orientationOrigin=null;}
async function enableMotion(){const D=window.DeviceOrientationEvent;if(!D){toast('当前设备不支持姿态数据，可以滑动画面体验。');return false;}try{if(typeof D.requestPermission==='function'){motionAllowed=(await D.requestPermission())==='granted';}else motionAllowed=true;}catch{motionAllowed=false;}if(!motionAllowed)toast('未获得移动权限，仍可滑动画面体验。');return motionAllowed;}
async function playVoice(){if(voice&&!voice.paused){stopVoice();return;}stopVoice();voice=new Audio(`./assets/${activeMode}-voice.wav`);const current=voice;voice.addEventListener('ended',stopVoice,{once:true});voice.addEventListener('error',()=>{if(voice===current){stopVoice();toast('语音暂不可用，页面文字仍可阅读。联网重开可重新缓存。');}},{once:true});document.querySelectorAll('.voice-button').forEach(b=>{b.classList.add('playing');b.setAttribute('aria-pressed','true');});try{await voice.play();}catch{if(voice===current){stopVoice();toast('未能播放，请再点一次并检查手机音量。');}}}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const action=b.dataset.action;
 if(['home','settings','privacy','about','result','child'].includes(action)){navigate(action);return;}
 if(action==='start'){startScan(b.dataset.mode);return;}
 if(action==='duration'){settings.duration=Number(b.dataset.value);save();render('settings');return;}
 if(action==='toggle'){const key=b.dataset.key;b.disabled=true;if(key==='motion'&&!settings.motion){settings.motion=await enableMotion();}else settings[key]=!settings[key];save();render('settings');return;}
 if(action==='reset'){settings={...DEFAULTS};motionAllowed=false;save();render('settings');toast('已恢复默认设置');return;}
 if(action==='voice'){playVoice();return;}
 if(action==='complete'){ensureAudio();if(settings.sound){beep(660,.17);beep(830,.17,.045,.14);beep(990,.3,.045,.28);}navigate('complete');return;}
 if(action==='install'){$('#install-dialog').showModal();return;}
 if(action==='close-dialog'){$('#install-dialog').close();return;}
 if(action==='update'&&updateWaiting){updateWaiting.postMessage({type:'SKIP_WAITING'});}
});
$('#install-dialog').addEventListener('click',e=>{if(e.target===$('#install-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopVoice();stopMotion();if(audioContext?.state==='running')audioContext.suspend().catch(()=>{});}else if(screen==='scan'||screen==='result'){startMotion();if(audioContext?.state==='suspended')audioContext.resume().catch(()=>{});}});
window.addEventListener('pagehide',()=>{stopScan();stopVoice();});
window.addEventListener('pageshow',e=>{if(e.persisted&&screen==='scan'){history.replaceState(null,'','#home');render('home');}});
function paintOffline(){const el=$('.offline-state');if(el){el.classList.toggle('ready',offlineReady);el.innerHTML=`<i></i>${offlineReady?(navigator.onLine?'离线已就绪':'离线模式 · 可以放心玩'):(!navigator.onLine?'尚未缓存，请联网打开':'正在准备离线资源')}`;}}
window.addEventListener('online',paintOffline);window.addEventListener('offline',paintOffline);
async function setupOffline(){if(!('serviceWorker'in navigator)){toast('当前浏览器不支持离线缓存，请使用 Safari。');return;}try{const reg=await navigator.serviceWorker.register('./sw.js',{scope:'./',updateViaCache:'none'});function ready(){offlineReady=true;paintOffline();}if(reg.active)ready();reg.addEventListener('updatefound',()=>{const worker=reg.installing;if(!worker)return;worker.addEventListener('statechange',()=>{if(worker.state==='installed'){if(navigator.serviceWorker.controller){updateWaiting=reg.waiting;if(screen==='home')render('home');}else ready();}});});if(reg.waiting){updateWaiting=reg.waiting;if(screen==='home')render('home');}await navigator.serviceWorker.ready;ready();}catch{const el=$('.offline-state');if(el)el.innerHTML='<i></i>缓存未完成，请联网刷新';}}
let refreshing=false;navigator.serviceWorker?.addEventListener('controllerchange',()=>{if(updateWaiting&&!refreshing){refreshing=true;location.reload();}});
const initial=location.hash.slice(1);render(['settings','privacy','about'].includes(initial)?initial:'home');if(!['settings','privacy','about'].includes(initial))history.replaceState(null,'','#home');setupOffline();
